#!/bin/bash

. lang.sh
. fn.sh


menu_main() {
	while [ "$ANSWER" != "x" ]
	do
		clear
		print_title MAIN
		echo "1. Httpd Virtual Hosts"
		echo "2. Brew Managment"
		echo "3. Services"
		echo ""
		echo "q. quit"
		echo ""
		question "Choose"
		case "$ANSWER" in
			1)
				menu_httpd
				;;
			2)
				menu_install
				;;
			3)
				menu_service
				;;
		esac
		ANSWER=""
	done
}

menu_httpd() {
	while [ "$ANSWER" != "x" ]
	do
		clear
		./bin.httpd.vhost.list.sh
		./bin.httpd.ps.sh
		echo ""
		echo "1. Add"
		echo "2. Edit"
		echo "3. Delete"
		echo "4. Load"
		echo "5. Save"
		echo "6. Restart"
		echo "7. Tail logs"
		sub_menu_trailer
		question "Choose"
		case $ANSWER in
			1|2)
				if [ "$ANSWER" = "2" ]
				then
					question "Edit"
					VHOST=$ANSWER
				else
					VHOST=`get_next_vhost_num`
				fi
				$BIN/bin.template.sh virtual_host $VHOST
				if [ $? -eq 0 ]
				then
					server_name=`get_var_from vhost.$VHOST.cfg OLM_SERVER_NAME`
					./bin.etc.hosts.add.sh $server_name
					rm $TD/virtual_host.answer
				else
					echo "FAILED: bin.httpd.vhost.add.py `perror $?`"
					press_return
				fi
				;;
			3)
				question "Delete"
				VHOST=$ANSWER
				server_name=`get_var_from vhost.$VHOST.cfg OLM_SERVER_NAME`
				echo "Deleting $server_name ($VHOST)"
				rm vhost.$VHOST
				rm vhost.$VHOST.cfg
				./bin.etc.hosts.delete.sh $server_name
				;;
			4)
				question "Sure, you may get dups"
				if [ "$ANSWER" = "y" ]
				then
					./bin.httpd.vhost.load.sh
				fi
				;;
			5)
				question "Sure"
				if [ "$ANSWER" = "y" ]
				then
					./bin.httpd.vhost.save.sh
				fi
				press_return
				;;
			6)
				brew services restart httpd
				press_return
				;;
			7)
				$BIN/bin.httpd.vhost.tail.sh
				press_return
				;;
			x)
				break
				;;
		esac
	done
}

menu_install() {
	while [ "$ANSWER" != "x" ]
	do
		clear
		print_title "Brew installations"
		echo "1. List installed versions"
		echo "-2. Install"
		echo "-3. Uninstall"
		echo "4. Update (all) brew packages"
		sub_menu_trailer
		question "Choose"
		case $ANSWER in
			1)
				$BIN/bin.brew.info.sh
				press_return
				;;
			4)
				$BIN/bin.brew.update.sh
				press_return
				;;
		esac
	done
}

menu_service() {
	while [ "$ANSWER" != "x" ]
	do
		clear
		print_title "Brew Services"
		$BIN/bin.brew.services.list.sh | tee $TD/brew.list.txt
		echo ""
		echo "1. Start all services"
		echo "2. Stop all services"
		echo "3. Start single services"
		echo "4. Stop single services"
		sub_menu_trailer
		question "Choose"
		case $ANSWER in
			1)
				$BIN/bin.brew.services.start_all.sh
				press_return
				;;
			2)
				$BIN/bin.brew.services.stop_all.sh
				press_return
				;;
			3)
				question "Which service"
				ser=$(head -$ANSWER $TD/brew.list.txt | tail -1 | awk '{print $2}' )
				$BIN/bin.brew.services.start.sh $ser
				press_return
				;;
			4)
				question "Which service"
				ser=$(head -$ANSWER $TD/brew.list.txt | tail -1 | awk '{print $2}' )
				$BIN/bin.brew.services.stop.sh $ser
				press_return
				;;
		esac
		rm -f $TD/brew.list.txt
	done
}

if [ ! -d "$TD" ]
then
	echo "Making temp directory: $TD"
	mkdir -p $TD
	if [ $? -ne 0 ]
	then
		echo "Failed to make temp folder $TD"
		exit 1
	fi
fi

menu_main

echo "Quitting..."
